#!/bin/bash

NC='\033[0m'

BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
GRAY='\033[0;37m'

DARK_GRAY='\033[1;30m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHT_BLUE='\033[1;34m'
LIGHT_PURPLE='\033[1;35m'
LIGHT_CYAN='\033[1;36m'
WHITE='\033[1;37m'

IFS=$'\n'
bat=($(acpi -b))

IFS=' '
bat0=(${bat[0]})
bat0_status=${bat0[2]::-1}
bat0_percent=${bat0[3]//[!0-9]/}
bat0_time=${bat0[4]}

bat1=(${bat[1]})
bat1_status=${bat1[2]::-1}
bat1_percent=${bat1[3]//[!0-9]/}
bat1_time=${bat1[4]}

result=""

if [ $bat0_status = "Charging" ]; then
  result+=""
elif [ $bat0_percent -gt 85 ]; then
  result+=" "
elif [ $bat0_percent -gt 50 ]; then
  result+=" "
elif [ $bat0_percent -gt 25 ]; then
  result+=" "
elif [ $bat0_percent -gt 15 ]; then
  result+=" "
else
  result+=" "
fi

result+=" $bat0_percent% $bat0_time"

if [ $bat1_status = "Charging" ]; then
  result+=" "
elif [ $bat1_percent -gt 85 ]; then
  result+="  "
elif [ $bat1_percent -gt 50 ]; then
  result+="  "
elif [ $bat1_percent -gt 25 ]; then
  result+="  "
elif [ $bat1_percent -gt 15 ]; then
  result+="  "
else
  result+="  "
fi

result+=" $bat1_percent% $bat1_time"

echo -e "I ${CYAN}love${NC} Stack Overflow"
echo "$result"

if [ $((bat0_percent + bat1_percent)) -lt 20 ]; then
  exit 33
elif [ $((bat0_percent + bat1_percent)) -lt 55 ]; then
  echo "#FFAE00"
fi

